import React from 'react';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react-native';
import { afterEach, beforeEach, expect, it, jest } from '@jest/globals';
import { apiFetch } from '@/core/api/client';
import { PasswordRecoveryScreen } from './password-recovery';
const mockReplace = jest.fn();
jest.mock('expo-router', () => ({ useRouter: () => ({ replace: mockReplace }) }));
jest.mock('lucide-react-native', () => ({ Eye: () => null, EyeOff: () => null }));
jest.mock('@/core/api/client', () => ({ apiFetch: jest.fn() }));
beforeEach(() => { jest.resetAllMocks(); });
afterEach(() => { jest.useRealTimers(); });
const requestCode = async () => {
  jest.mocked(apiFetch).mockResolvedValueOnce({ request_id: 'request', mensagem: 'Resposta neutra', reenviar_apos: 60 });
  await render(<PasswordRecoveryScreen />);
  await fireEvent.changeText(screen.getByLabelText('E-mail da conta'), ' Synthetic@example.invalid ');
  await fireEvent.press(screen.getByRole('button', { name: 'Solicitar código' }));
  await waitFor(() => expect(screen.getByLabelText('Código de oito dígitos')).toBeTruthy());
};
it('requests anonymously, keeps resend disabled for sixty seconds and returns to login', async () => {
  await requestCode();
  expect(apiFetch).toHaveBeenCalledWith('/v2/auth/password-recovery/request', expect.objectContaining({ authenticated: false, body: JSON.stringify({ email: 'synthetic@example.invalid' }) }));
  expect(screen.getByRole('button', { name: 'Reenviar em 60s' })).toBeDisabled();
  await fireEvent.press(screen.getByRole('button', { name: 'Voltar ao login' }));
  expect(mockReplace).toHaveBeenCalledWith('/(public)/login');
});
it('checks confirmation, preserves fields on failure and clears secrets after success without signing in', async () => {
  await requestCode();
  await fireEvent.changeText(screen.getByLabelText('Código de oito dígitos'), '12345678');
  await fireEvent.changeText(screen.getByLabelText('Nova senha'), 'Synthetic!1');
  await fireEvent.changeText(screen.getByLabelText('Confirmar nova senha'), 'different');
  await fireEvent.press(screen.getByRole('button', { name: 'Redefinir senha' }));
  expect(screen.getByText('As senhas precisam ser iguais.')).toBeTruthy();
  expect(apiFetch).toHaveBeenCalledTimes(1);
  await fireEvent.changeText(screen.getByLabelText('Confirmar nova senha'), 'Synthetic!1');
  jest.mocked(apiFetch).mockRejectedValueOnce(new Error('Falha recuperável'));
  await fireEvent.press(screen.getByRole('button', { name: 'Redefinir senha' }));
  expect(screen.getByLabelText('Código de oito dígitos').props.value).toBe('12345678');
  expect(screen.getByLabelText('Nova senha').props.value).toBe('Synthetic!1');
  jest.mocked(apiFetch).mockResolvedValueOnce({ mensagem: 'Senha redefinida' });
  await fireEvent.press(screen.getByRole('button', { name: 'Redefinir senha' }));
  expect(screen.queryByLabelText('Nova senha')).toBeNull();
  expect(screen.getByText('Entre com a nova senha. As sessões anteriores foram encerradas.')).toBeTruthy();
  expect(mockReplace).not.toHaveBeenCalled();
});
it('guards duplicate requests before the next render and allows resend only after the interval', async () => {
  jest.useFakeTimers();
  let resolve: (value: unknown) => void = () => undefined;
  jest.mocked(apiFetch).mockImplementationOnce(() => new Promise(done => { resolve = done; }) as never);
  await render(<PasswordRecoveryScreen />);
  await fireEvent.changeText(screen.getByLabelText('E-mail da conta'), 'synthetic@example.invalid');
  const button = screen.getByRole('button', { name: 'Solicitar código' });
  await act(async () => { await fireEvent.press(button); await fireEvent.press(button); });
  expect(apiFetch).toHaveBeenCalledTimes(1);
  await act(async () => resolve({ request_id: 'first', mensagem: 'Resposta neutra', reenviar_apos: 60 }));
  await act(async () => jest.advanceTimersByTime(60_000));
  expect(screen.getByRole('button', { name: 'Reenviar código' })).toBeEnabled();
  jest.mocked(apiFetch).mockResolvedValueOnce({ request_id: 'second', mensagem: 'Resposta neutra', reenviar_apos: 60 });
  await fireEvent.press(screen.getByRole('button', { name: 'Reenviar código' }));
  expect(apiFetch).toHaveBeenCalledTimes(2);
});
